server:
  port: 8000
spring:
  application:
    name: microservice-simple-provider-user
management:
  security:
    enabled: false
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRA