server:
  port: 8091

spring:
  dubbo:
    application:
      name: provider
    registry:
      address: zookeeper://127.0.0.1:2181   # 注册中心地址
    protocol:
      name: dubbo     # dubbo 协议
      port: 20880
    scan: cn.ecomb.dubbo.service    # 声明需要暴露的服务接口
